### ISSUE TITLE
CSS classes are assigned at multiple levels, not just to outer container

### ISSUE THREAD

**Issue by hughc** [bostondv/enhanced-text-widget#8]
Hi,
Love your widget, it's in my project bootstrap; it's great for widgetized homepage layouts in particular.

I'm unsure whether this has anything specific to do with the Genesis Framework that I often use, and the tags that it produces, but I find that the `$cssClass` values are added at multiple levels, ie:

```
<section id="enhancedtextwidget-3" class="fishing-trips link-block one-third widget widget_text enhanced-text-widget">
    <div class="fishing-trips link-block one-third widget-wrap">
        <div class="textwidget widget-text">
            <a href="#"><div class="inner">Fishing<br>Trips</div></a>
        </div>
    </div>
</section>
```

In this case `fishing-trips link-block one-third` appear twice, which is awkward as one-third is a relatively generic grid class that sets a percentage width. 

I've forked a copy of the repo to add an extra param to optionally apply the styles only to the first wrapper tag:

https://github.com/hughc/enhanced-text-widget/commit/013cf73122802fd71af7fcb6886d50c8918aaf2f

Let me know if you can see the issue and would like a pull request.

**Comment by bostondv** [comment]
Hey! Sorry for not responding sooner. This is most likely something with your theme, it does not do this on the WordPress default theme with v4.8.

See "test-class" here:

<img width="431" alt="screen shot 2017-09-21 at 10 52 28 pm" src="https://user-images.githubusercontent.com/133814/30727514-ae89a156-9f1f-11e7-99c8-9d0365991141.png">

**Comment by hughc** [comment]
OK, my apologies; I work with subthemes of Genesis all the time, and was unaware that it's markup is non-standard. I can be more specific now.

The extra CSS class feature is not compatible with any Genesis theme, as the `$before_widget` code for all Genesis widgets includes an extra `<div class='widget-wrap'>`, and your str_replace code will add any nominated classes to both `<div>`s in the `$before_widget` , ie: 

![image](https://user-images.githubusercontent.com/2739217/30792890-2c44fb8e-a201-11e7-9c6d-3f0c647cd4cd.png)

Not sure if there's a clean way to resolve this, but at the end of the day, there's an underlying assumption in the use of `str_replace` that there's a single element wrapping the widget content, but Wordpress does not prohibit the use of multiple divs.

I'm using a private fork of the plugin in client projects now, disconnected from wordpress.org updates, but it would be useful to either update the docs to mention the incompatibility or else consider the PR  that you closed. My proposed code could be simplified to remove the checkbox and just use the `str_replace_first` function instead of `str_replace`, to improve compatibility.
